
@base_url=http://localhost:3000/api

GET {{base_url}}/items/1

###

GET {{base_url}}/items/

###

POST {{base_url}}/items
Content-Type: application/json

{
  "name": "Test item",
  "description": "Test",
  "category": "Testing",
  "price": 5,
  "quantity": 5
}

###

PUT {{base_url}}/items/1
Content-Type: application/json

{
  "image": "keychain_cat.jpg"
}

###

DELETE  {{base_url}}/items/3